### ISSUE TITLE
improve performance

### ISSUE THREAD

**Issue by deflaux** [Bioconductor/GoogleGenomics#17]
This package is in active development and there are some inefficiencies in a few places (e.g., the code that accumulates multiple pages of variants and reads).  But we'll tackle improving performance a bit when the code settles down a bit more.

**Comment by siddharthab** [comment]
Going forward, performant access to the API is predicated by using the RPC interface instead of the REST interface:
http://www.grpc.io/
https://cloud.google.com/genomics/reference/rpc/

I am working on writing a running example based on gRPC.

**Comment by ttriche** [comment]
Does this mean that Avro is getting canned?  And an R gRPC client coming?

AWESO^H^H^H^H^Hthat is an eminently logical implementation decision.



Statistics is the grammar of science.
Karl Pearson <http://en.wikipedia.org/wiki/The_Grammar_of_Science>

On Mon, Jul 6, 2015 at 4:31 PM, Siddhartha Bagaria <notifications@github.com

**Comment by siddharthab** [comment]
I am trying to base the gRPC R package on the RProtoBuf package. But there are several changes needed there too. A generic package might be a little farther off but I can get the GoogleGenomics endpoints running soon-ish.

**Comment by pgrosu** [comment]
Sid, how about just basically writing a wrapper via [Rcpp](http://cran.r-project.org/web/packages/Rcpp/index.html)?  Autonomy is always more fun :)

Tim, I think it's an evolution :)

**Comment by siddharthab** [comment]
Paul, that is what will happen if I base it on the RProtoBuf package. I need the package for the interface to the C protocol buffers library.

**Comment by pgrosu** [comment]
Gotcha!  Super-excited to see what you come up with :)

Thx,
~p

**Comment by siddharthab** [comment]
Resolved with #56
