### ISSUE TITLE
Error [...] key 60 (char '<') not in lookup table

### ISSUE THREAD

**Issue by danielemerico** [Bioconductor/GoogleGenomics#32]
We get this rather cryptic error message after exporting variants from a Google genomics object:

##
granges <- variantsToGRanges(variants)

Error in .Call2("new_XString_from_CHARACTER", classname, x, start(solved_SEW), : 
key 60 (char '<') not in lookup table
##

If I have to guess, it may be due to alternateBases = "<NON_REF>" for reference intervals, when importing variants from a gVCF into the google genomics object.

Data are access-restricted, so I can't provide more information.

**Comment by deflaux** [comment]
@danielemerico Is it correct that the goal is to annotate variants and ignore the non-variant segments?

If so, here is a workaround:
```
# Filter non-variant segments out
onlyVariants <- variants[lapply(variants, function(v){ v$alternateBases[[1]]}) != "<NON_REF>"]
granges <- variantsToGRanges(onlyVariants)
```

@ttriche here's the stack trace.  Do you have any BioConductor-specific suggestions as to how we might work with data containing non-variant segments?  Is filtering them out before hand the common approach?  I would also imagine we would hit this if the alternate allele value was `<DEL>`  Thanks in advance for any pointers/advice!

```
> granges <- variantsToGRanges(variants)
Error in .Call2("new_XString_from_CHARACTER", classname, x, start(solved_SEW),  : 
  key 60 (char '<') not in lookup table
Calls: variantsToGRanges ... XString -> XString -> .charToXString -> .Call2 -> .Call
> traceback()
19: .Call(.NAME, ..., PACKAGE = PACKAGE)
18: .Call2("new_XString_from_CHARACTER", classname, x, start(solved_SEW), 
        width(solved_SEW), get_seqtype_conversion_lookup("B", seqtype), 
        PACKAGE = "Biostrings")
17: .charToXString(seqtype, x, start, end, width)
16: XString(seqtype, x)
15: XString(seqtype, x)
14: .oneSeqToXStringSet(seqtype, x, start, end, width, use.names)
13: .charToXStringSet(seqtype, x, start, end, width, use.names)
12: XStringSet(seqtype, unlisted_y)
11: XStringSet(seqtype, unlisted_y)
10: .new_XStringSetList_from_list(seqtype, x)
9: XStringSetList("DNA", ..., use.names = use.names)
8: DNAStringSetList(v$alternateBases)
7: DataFrame(...)
6: newGRanges("GRanges", seqnames = seqnames, ranges = ranges, strand = strand, 
       mcols = DataFrame(...), seqlengths = seqlengths, seqinfo = seqinfo)
5: GRanges(seqnames = Rle(as.character(v$referenceName), 1), ranges = IRanges(start = position, 
       end = as.integer(v$end)), REF = DNAStringSet(v$referenceBases), 
       ALT = DNAStringSetList(v$alternateBases), QUAL = as.numeric(v$quality), 
       FILTER = as.character(v$filter))
4: FUN(X[[1L]], ...)
3: lapply(variants, variantsToGRangesHelper)
2: do.call("c", lapply(variants, variantsToGRangesHelper))
1: variantsToGRanges(variants)
```

**Comment by pgrosu** [comment]
@deflaux, it's probably just easier to use FilterRules via VariantTools or directly from IRanges:

http://www.bioconductor.org/packages/release/bioc/html/VariantTools.html

http://www.bioconductor.org/packages/release/bioc/html/IRanges.html

~p

**Comment by danielemerico** [comment]
Workaround works. I tried something similar, but this implementation does not break the object while mine did. More than sufficient for current purposes.

**Comment by deflaux** [comment]
Closing this issue in favor of https://github.com/Bioconductor/GoogleGenomics/issues/46
