### ISSUE TITLE
Might want to update to the new location...

### ISSUE THREAD

**Issue by pgrosu** [Bioconductor/GoogleGenomics#40]
Hi Sid,

Congratulations on the new location, but probably might want to let Travis know of the new location ([Bioconductor/GoogleGenomics](https://github.com/Bioconductor/GoogleGenomics)), since it's still looking at the old one (https://travis-ci.org/googlegenomics/api-client-r) and cannot build it [i.e. it's saying *build inaccessible*].  

Probably also updating everything else to point to the new one too would be nice - i.e. the Readme still points to:
```
devtools::install_github("googlegenomics/api-client-r")
```
Thanks,
~p

**Comment by siddharthab** [comment]
Done. Thanks for filing this. :)

**Comment by pgrosu** [comment]
Cool, thanks for the update - yeah I was getting bored the other day :)

Have a great weekend Sid!
`p
