### ISSUE TITLE
Update getVariants* calls to accept a variantSetId instead of datasetId

### ISSUE THREAD

**Issue by mbookman** [Bioconductor/GoogleGenomics#48]
There used to be one variantSet per dataset and the IDs were the same.
The v1beta2 and v1 variant search APIs accept a variant set ID, not a dataset ID.

See:
  https://cloud.google.com/genomics/v1beta2/reference/variants/search
  https://cloud.google.com/genomics/reference/rest/v1/variants/search

The getVariants\* calls in R/variants.R should replace the datasetId parameter with variantSetId.

**Comment by siddharthab** [comment]
Resolved in #56
